### ISSUE TITLE
tests cannot run on non-release versions of node

### ISSUE THREAD

**Issue by misterdjules** [joyent/mdb_v8#72]
Here's an example of the error that is thrown when running tests with e.g a development version of node:

```
[jgilli@dev ~/mdb_v8]$ ../node/node --version
v7.0.0-pre
[jgilli@dev ~/mdb_v8]$ ../node/node test/standalone/tst.jsclosure.js 

assert.js:90
  throw new assert.AssertionError({
  ^
AssertionError: true == false
    at getNodeVersions (/home/jgilli/mdb_v8/test/lib/runtime-versions.js:24:9)
    at getRuntimeVersions (/home/jgilli/mdb_v8/test/lib/runtime-versions.js:72:9)
    at Object.<anonymous> (/home/jgilli/mdb_v8/test/standalone/tst.jsclosure.js:20:24)
    at Module._compile (module.js:541:32)
    at Object.Module._extensions..js (module.js:550:10)
    at Module.load (module.js:458:32)
    at tryModuleLoad (module.js:417:12)
    at Function.Module._load (module.js:409:3)
    at Module.runMain (module.js:575:10)
    at run (node.js:340:7)
[jgilli@dev ~/mdb_v8]$
```

The problem is that the code that parses node versions [assumes release versions only](https://github.com/joyent/mdb_v8/blob/master/test/lib/runtime-versions.js#L15-L24).

**Comment by misterdjules** [comment]
Fixed by d9e700b45c414716eeb70d308db75a49c5de1ef5.
