### ISSUE TITLE
tst.jsclosure.js breaks with long workspace path names

### ISSUE THREAD

**Issue by davepacheco** [joyent/mdb_v8#95]
When doing a sanity check for releasing v1.2.0, I ran into this test failure:

```
dap@b44c74d6 mdb_v8_release $ cat /var/tmp/catest.57826/failure.0/README 
/home/dap/mdb_v8_release/test/standalone/tst.jsclosure.js failed: test returned 8
dap@b44c74d6 mdb_v8_release $ cat /var/tmp/catest.57826/failure.0/*.err
> ::load /home/dap/mdb_v8_release/build/ia32/mdb_v8.so
mdb_v8 version: 1.2.0 (release, from f6c6dd3)
V8 version: 3.14.5.9
Autoconfigured V8 support from target
C++ symbol demangling enabled

> ::jsfunctions -n myClosure ! awk 'NR == 2{ print $1 }'
8f793f85

> 8f793f85::jsclosure
    "str": 81727789: "hello world"
    "count": 12: 9

> 8f793f85::v8function
8f793f85: JSFunction: myClosure
defined at /home/dap/mdb_v8_release/test/standalone/tst.jsclosure.js position 81
4
context: 8f793f65
shared scope_info: a3939dcd
code: ba25d7c1
instructions: [ba25d800, ba25d898)

> 8f793f65::v8context
closure function: 8f786235 (JSFunction)
previous context: 8f7861cd (FixedArray)
extension: 0 (SMI: value = 0)
global object: a3909619 (JSGlobalObject)
    slot 0: 81727789 (SeqAsciiString)
    slot 1: 12 (SMI: value = 9)

> 8f786235::v8function ! awk '/shared scope_info:/{ print $3 }'
a3939d81

> a3939d81::v8scopeinfo
1 parameter
    parameter 0: 8171c9d9 ("str")
1 stack local variable
    stack local variable 0: 817276c1 ("myClosure")
2 context local variables
    context local variable 0: 8171c9d9 ("str")
    context local variable 1: 817276ad ("count")

> ::findjsobjects -p __bind | ::findjsobjects | ::jsprint -ad1 __bind
a3908091: undefined
a39080a1: true
8f793ebd: function <anonymous> (as b)

> 8f793ebd::jsfunction
bound function that wraps: 8f786235
with "this" = 8f793e91 (JSObject: Object)
      arg0  = 81727729 (SeqAsciiString)
      arg1  = 81727741 (SeqAsciiString)
      arg2  = 81727759 (SeqAsciiString)
      arg3  = 81727771 (SeqAsciiString)

{ this: '8f793e91',
  arg0: '81727729',
  arg1: '81727741',
  arg2: '81727759',
  arg3: '81727771' }
> 8f786235::jsfunction;8f793e91::jsprint;81727729::jsprint;81727741::jsprint;81727759::jsprint;81727771::jsprint
function: doStuff
defined at /home/dap/mdb_v8_release/test/standalone/tst.jsclosure.js position 77
2
{
    "thisObj": true,
}
"arg1value"
"arg2value"
"arg3value"
"arg4value"


assert.js:93
  throw new assert.AssertionError({
        ^
AssertionError: ["function: doStuff","2","{","    \"thisObj\": true,","}","\"arg1value\"","\"arg2value\"","\"arg3value\"","\"arg4value\"",""] deepEqual ["function: doStuff","{","    \"thisObj\": true,","}","\"arg1value\"","\"arg2value\"","\"arg3value\"","\"arg4value\"",""]
    at Array.gotJsFunctionValues [as 9] (/home/dap/mdb_v8_release/test/standalone/tst.jsclosure.js:350:9)
    at doWork (/home/dap/mdb_v8_release/test/standalone/tst.jsclosure.js:123:25)
    at Socket.<anonymous> (/home/dap/mdb_v8_release/test/standalone/tst.jsclosure.js:104:4)
    at Socket.emit (events.js:95:17)
    at Socket.<anonymous> (_stream_readable.js:765:14)
    at Socket.emit (events.js:92:17)
    at emitReadable_ (_stream_readable.js:427:10)
    at emitReadable (_stream_readable.js:423:5)
    at readableAddChunk (_stream_readable.js:166:9)
    at Socket.Readable.push (_stream_readable.js:128:10)
```

That's strange, given all the testing I just did for #44.  The key is this block of output:

```
> 8f786235::jsfunction;8f793e91::jsprint;81727729::jsprint;81727741::jsprint;81727759::jsprint;81727771::jsprint
function: doStuff
defined at /home/dap/mdb_v8_release/test/standalone/tst.jsclosure.js position 77
2
{
    "thisObj": true,
}
```

The test case looks for the line that contains the full path to tst.jsclosure.js.  It verifies that it matches the expected form with a regex, and then it strips it out.

But what's up with that extra "2" line?  The problem is that we're talking to mdb via a pipe, and in that mode, mdb cannot tell what the terminal width is (since there isn't one), so it assumes that the width is 80 columns and inserts a newline at that point.  If I rename my workspace to "mdb_v8_rel" instead of "mdb_v8_release", the test works fine.

This behavior has been changed in more modern versions of mdb (I'm on joyent_20160830T004914Z), but it's easy enough to add a workaround by explicitly setting a very large terminal width in our mdb invocation.

**Comment by davepacheco** [comment]
Fix: https://cr.joyent.us/2484

Patchset 1 is `make prepush`-clean.
